#!/usr/bin/env bash
# Print AI-handoff text: a compact, paste-into-a-prompt menu of the data backends this
# stack runs, so another assistant (e.g. a separate Claude Code session) can read it, pick
# only what its task needs, and connect/debug directly. Generated from .env — the single
# source of truth — so it never drifts. Live status is read from `docker compose ps`.
# The text is written to AI-HANDOFF-PROMPT.md (gitignored, so you can attach/reference it)
# and also echoed to stdout.
#   ./scripts/ai.sh            # full handoff text for every backend
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f .env ] || { echo "No .env found. Run 'make init' first." >&2; exit 1; }
set -a; . ./.env; set +a

DIR="$PWD"

# Where the handoff is saved (gitignored — see .gitignore). Regenerated on every run.
OUT="AI-HANDOFF-PROMPT.md"

# The data backends (excludes the *-ui helper containers).
DATA_SERVICES="db-postgres s3-garage cache-valkey queue-rabbitmq stream-kafka search-opensearch"

# Which services are running right now (best-effort; empty if docker/compose is unavailable).
RUNNING=""
if command -v docker >/dev/null 2>&1; then
  RUNNING="$(docker compose ps --services --status running 2>/dev/null || true)"
fi
is_up() { printf '%s\n' "$RUNNING" | grep -qx "$1"; }
mark()  { is_up "$1" && echo "up" || echo "DOWN — start it with 'make up'"; }

up_count=0; total=0
for s in $DATA_SERVICES; do total=$((total+1)); is_up "$s" && up_count=$((up_count+1)); done

# Build the handoff once, redirecting the whole group to the file (a single redirection on
# a brace group — no subshell — so the helper functions/vars stay in scope). Then echo the
# saved file to stdout so `make ai` both writes and prints.
{
# --- Static framing (quoted heredoc: backticks stay literal, no expansion) -------------
cat <<'EOF'
<!-- Local data backends — context for an AI assistant. Generated by `make ai`. -->
# Local data backends (already running)

You're helping a developer who already has a disposable LOCAL data stack running on this
machine. Below is a menu of backends. Read it, pick ONLY the ones your task needs, and
connect to them directly — no setup required. This is throwaway local dev: read, write,
query, create buckets/topics/indexes, and reset freely. It is NOT production — never expose
it, depend on its durability, or commit the secrets below.
EOF

# --- Dynamic header line (vars; no backticks) -----------------------------------------
printf '\nStack location: %s  (run the `make` commands there)\n' "$DIR"
printf 'Live status: %s/%s backends up.\n' "$up_count" "$total"

cat <<'EOF'

## Backends — pick what you need
EOF

# --- Per-service blocks (unquoted heredocs: $vars expand; avoid backticks) -------------
cat <<EOF

### Postgres — relational database  [$(mark db-postgres)]
Use for : relational/transactional data, SQL, anything you'd put in a normal RDBMS.
Host    : postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:$PGPORT/$POSTGRES_DB?sslmode=disable
InDocker: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db-postgres:5432/$POSTGRES_DB?sslmode=disable
Debug   : make debug CMD='psql -c "\\dt"'   (no host psql needed — runs in the wired debug box)
UI      : http://localhost:$PGADMIN_PORT  (pgAdmin, opens pre-connected)
Note    : no TLS — keep sslmode=disable (Go lib/pq must set it explicitly).

### S3 / Garage — object storage  [$(mark s3-garage)]
Use for : blobs, file uploads, artifacts, anything S3-shaped.
Endpoint: http://localhost:$GARAGE_S3_PORT   (in-Docker: http://s3-garage:3900)   region=$GARAGE_REGION   bucket=$GARAGE_BUCKET
Creds   : AWS_ACCESS_KEY_ID=$GARAGE_ACCESS_KEY_ID  AWS_SECRET_ACCESS_KEY=$GARAGE_SECRET_ACCESS_KEY
Debug   : make debug CMD='aws s3 ls s3://\$GARAGE_BUCKET'   (aws/mc pre-wired in the debug box)
UI      : http://localhost:$GARAGE_UI_PORT  (opens straight in)
Note    : path-style addressing REQUIRED (forcePathStyle / s3ForcePathStyle / addressing_style=path); plain http.

### Valkey — Redis-compatible cache / KV  [$(mark cache-valkey)]
Use for : caching, ephemeral key/value, rate limits, lightweight queues. Speaks the Redis protocol.
Host    : redis://default:$VALKEY_PASSWORD@localhost:$VALKEY_PORT/0
InDocker: redis://default:$VALKEY_PASSWORD@cache-valkey:6379/0
Debug   : make debug CMD='redis-cli -h cache-valkey ping'   (auth preset in the debug box)
UI      : http://localhost:$VALKEY_UI_PORT  (redis-commander)
Note    : plaintext — use redis:// (not rediss://); auth is the password only.

### RabbitMQ — AMQP message broker  [$(mark queue-rabbitmq)]
Use for : task queues, pub/sub, work distribution (AMQP 0-9-1).
Host    : amqp://$RABBITMQ_USER:$RABBITMQ_PASSWORD@localhost:$RABBITMQ_PORT/%2F
InDocker: amqp://$RABBITMQ_USER:$RABBITMQ_PASSWORD@queue-rabbitmq:5672/%2F
Debug   : make debug CMD='curl -s -u \$RABBITMQ_USER:\$RABBITMQ_PASSWORD queue-rabbitmq:15672/api/overview | jq .'
UI      : http://localhost:$RABBITMQ_MANAGEMENT_PORT  (login: $RABBITMQ_USER / $RABBITMQ_PASSWORD)
Note    : trailing /%2F is the default vhost '/'; the management UI is also an HTTP API under /api.

### Kafka — event-streaming broker  [$(mark stream-kafka)]
Use for : event streaming, logs, high-throughput pub/sub. Single node, RF=1.
Bootstrap: localhost:$KAFKA_PORT   (in-Docker: stream-kafka:9092)   plaintext, no auth
Topics  : ${KAFKA_TOPICS:-<none pre-created; broker auto-creates on first produce (RF=1)>}
Debug   : make debug CMD='kafka-topics.sh --bootstrap-server \$KAFKA_BOOTSTRAP --list'   (or: kcat -b \$KAFKA_BOOTSTRAP -L)
UI      : http://localhost:$KAFKA_UI_PORT  (kafbat)
Note    : replication.factor and min.insync.replicas must be 1 here — treat them as config, not constants.

### OpenSearch — search / analytics engine  [$(mark search-opensearch)]
Use for : full-text search, log/analytics queries, vector-ish search.
REST    : http://localhost:$OPENSEARCH_PORT   (in-Docker: http://search-opensearch:9200)   no auth
Debug   : make debug CMD='curl -s \$OPENSEARCH_URL/_cluster/health?pretty'
UI      : http://localhost:$OPENSEARCH_DASHBOARDS_PORT  (OpenSearch Dashboards)
Note    : use an OpenSearch client (NOT the Elasticsearch 8+ client). Set number_of_replicas=0 on indexes to stay green.
EOF

# --- Static footer (quoted heredoc) ----------------------------------------------------
cat <<'EOF'

## Verify & operate (run in the stack location above)
make status              # live container health
make conn ONLY=<svc>     # full per-language connection details for one service
make logs SVC=<svc>      # tail a service's logs  (svc = db-postgres|s3-garage|cache-valkey|queue-rabbitmq|stream-kafka|search-opensearch)
make debug               # interactive shell with EVERY backend CLI preloaded & wired (psql, aws, mc, redis-cli, kcat, kafka-*.sh, amqp-*, curl)
make debug CMD='<cmd>'   # run one command in that wired shell, e.g. make debug CMD='psql -c "\dt"'  (no host tools needed)
make down                # stop the stack but KEEP data
make reset && make up    # wipe ALL data volumes and restart fresh (destructive)

Prefer `make debug CMD='...'` for poking the backends: clients are pre-wired to the compose
network with creds from .env, so nothing needs hosts/ports/passwords typed and the host needs
no CLIs installed. Inside it, reach services by name (db-postgres, s3-garage, cache-valkey,
queue-rabbitmq, stream-kafka, search-opensearch).

## Ground rules
- Disposable local stack — use and debug it freely (read / write / reset are all fine).
- It is NOT production: plaintext, no TLS, weak local creds by design. Don't expose it or rely on durability.
- Never commit `.env` or any secret printed above.
EOF
} > "$OUT"

cat "$OUT"
printf '\n[handoff written to %s — attach it or append its contents to your prompt]\n' "$OUT" >&2
